### ISSUE TITLE
kernel 6.x problem

### ISSUE THREAD

**Issue by gilcu3** [Bluetooth-Devices/bleak-retry-connector#91]
**Describe the bug**
I am using this module as part of a custom component for a ble light (govee) in home assistant. Since changing to the linux kernel 6.x (archlinux), all works fine for some minutes, then stops working with the following error in the logs:

```
Mar 02 15:04:51 msigil hass[1360]: bleak.exc.BleakError: No backend with an available connection slot that can reach address 7C:A6:B0:5D:32:27 was found
Mar 02 15:04:51 msigil hass[1360]: The above exception was the direct cause of the following exception:
Mar 02 15:04:51 msigil hass[1360]: Traceback (most recent call last):
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1826, in catch_exceptions
Mar 02 15:04:51 msigil hass[1360]:     await coro_or_task
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/core.py", line 1845, in _execute_service
Mar 02 15:04:51 msigil hass[1360]:     await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
Mar 02 15:04:51 msigil hass[1360]:     await service.entity_service_call(
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 686, in entity_service_call
Mar 02 15:04:51 msigil hass[1360]:     future.result()  # pop exception if have
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 961, in async_request_call
Mar 02 15:04:51 msigil hass[1360]:     await coro
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/service.py", line 726, in _handle_entity_call
Mar 02 15:04:51 msigil hass[1360]:     await result
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/homeassistant/components/light/__init__.py", line 572, in async_handle_light_on_service
Mar 02 15:04:51 msigil hass[1360]:     await light.async_turn_on(**filter_turn_on_params(light, params))
Mar 02 15:04:51 msigil hass[1360]:   File "/home/homeassistant/.homeassistant/custom_components/govee_btled_H613B/light.py", line 138, in async_turn_on
Mar 02 15:04:51 msigil hass[1360]:     await self._device.turn_on()
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/govee_btled_H613B/govee_btled_H613B.py", line 275, in turn_on
Mar 02 15:04:51 msigil hass[1360]:     await self._send(LedMsgType.COMMAND, LedCommand.POWER, [0x1])
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/govee_btled_H613B/govee_btled_H613B.py", line 218, in _send
Mar 02 15:04:51 msigil hass[1360]:     await self._ensure_connected()
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/govee_btled_H613B/govee_btled_H613B.py", line 173, in _ensure_connected
Mar 02 15:04:51 msigil hass[1360]:     client = await establish_connection(
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 419, in establish_connection
Mar 02 15:04:51 msigil hass[1360]:     _raise_if_needed(name, device.address, exc)
Mar 02 15:04:51 msigil hass[1360]:   File "/home/rey/homeassistant/lib/python3.10/site-packages/bleak_retry_connector/__init__.py", line 311, in _raise_if_needed
Mar 02 15:04:51 msigil hass[1360]:     raise BleakOutOfConnectionSlotsError(
Mar 02 15:04:51 msigil hass[1360]: bleak_retry_connector.BleakOutOfConnectionSlotsError: GBK_H613B_3227 - 7C:A6:B0:5D:32:27: Failed to connect: No backend with an available connection slot that can reach address 7C:A6:B0:5D:32:27 was found: The proxy/adapter is out of connection slots; Add additional proxies near this device
```

**To Reproduce**
Boot in any kernel 6.x, turn on the ble light.

**Additional context**
I am using the internal intel wifi+bluetooth card, and core installation of homeassistant, version 2023.03
```
Bus 001 Device 005: ID 8087:0aa7 Intel Corp. Wireless-AC 3168 Bluetooth
'''
Reloading the bluetooth integration in Homeassistant makes it work for a few minutes, then goes back to the aforementioned error.

**Comment by gilcu3** [comment]
I am closing this, as I discovered that the issue happens as well just using `bleak`, and that by doing `bluetoothctl -- scan on` it is fixed while the scan lasts.
